version: 2
updates:
  # Enable version updates for bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
  # Enable version updates for actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "gh-actions"
