AllCops:
  Include:
  - 'Rakefile'
  - '*.gemspec'
  - 'lib/**/*.rb'
  - 'spec/**/*.rb'
  Exclude:
  - 'bin/**/*'
  - 'smoke/**/*'
  - 'Gemfile'
  - 'vendor/bundle/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Rails:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  EnforcedStyleForEmptyBraces: space

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
  - 'spec/**/*.rb'

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 120

Metrics/ParameterLists:
  Max: 6

Naming/UncommunicativeMethodParamName:
  AllowedNames: [io, id, db, ex]

Naming/FileName:
  Exclude:
  - lib/influxdb-rails.rb

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
  Exclude:
  - "spec/**/*.rb"

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Exclude:
  - "spec/**/*.rb"
